### PR TITLE
compile rt_default & rt_redirect extension

### PR DESCRIPTION
**Pull request by Crazyokd**

### CODE REVIEW

**Comment by acetcom** [comment]
@Crazyokd 

I'm not familiar with all the extension modules in freeDiameter, could you explain what adding rt_default and rt_redirect would do for open5gs? 

Thanks a lot!
Sukchan

**Comment by Crazyokd** [comment]
the `rt_default` and `rt_redirect` extensions are used for diameter routing control.
the common use case is as a DRA(Diameter routing agent).

In the LTE roaming occasion, the DRA can connect multiple MME and HSS and use corresponding configuration to control which HSS an AIR or ULR from the MME should be forwarded to. 
Below is a DRA routing configuration example, which use `username` AVP to determine which node should be forwarded to:
```
un=["^46001.*"] : "hss.localdomain" += FINALDEST;
```
Also you can use it for load balance.
below is some related link which helpful for me:
- https://nickvsnetworking.com/diameter-routing-agents-why-you-need-them-and-how-to-build-them-part-1/
- https://github.com/freeDiameter/freeDiameter/blob/master/doc/rt_default.conf.sample

I am a LTE newbie, but I really use it with open5gs implement my purpose.

**Comment by Crazyokd** [comment]
I just browsed to [#2195](https://github.com/open5gs/open5gs/issues/2195). I believe this extension will useful for it.

**Comment by acetcom** [comment]
@Crazyokd 

I think it's a bad idea to modify rt_default-host.h.in directly. What do you think about making the followings changes?

```diff
$ diff --git a/extensions/rt_default/meson.build b/extensions/rt_default/meson.build
index 28c3d67..9d79aa4 100644
--- a/extensions/rt_default/meson.build
+++ b/extensions/rt_default/meson.build
@@ -2,8 +2,7 @@ if cc.has_function('regexec', prefix : '#include <regex.h>')
   conf_data = configuration_data()
   conf_data.set('HAVE_REG_STARTEND', 1)
 endif
-configure_file(input : 'rt_default-host.h.in',
-                output : 'rt_default-host.h',
+configure_file(output : 'rt_default-host.h',
                 configuration : conf_data)
```

freeDiameter is using an older version of the syntax.

```
$ ninja        
[138/3941] Generating from 'subproject...er/extensions/rt_default/rtd_conf.y'..
../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y:42.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
   42 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y:49.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
   49 | %pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
[3941/3941] Linking target tests/non3gpp/non3gpp
```

You might consider modifying it as follows.

```diff
$ diff --git a/extensions/rt_default/rtd_conf.y b/extensions/rt_default/rtd_conf.y
index e02303c..1ef24ab 100644
--- a/extensions/rt_default/rtd_conf.y
+++ b/extensions/rt_default/rtd_conf.y
@@ -39,14 +39,14 @@
 
 /* For development only : */
 %debug 
-%error-verbose
+%define parse.error verbose
 
 /* The parser receives the configuration file filename as parameter */
 %parse-param {char * conffile}
 
 /* Keep track of location */
 %locations 
-%pure-parser
+%define api.pure
 
 %{
 #include "rt_default.h"
```

Please let me know if you have any other questions.

Thanks a lot!
Sukchan

**Comment by Crazyokd** [comment]
@acetcom 
> I think it's a bad idea to modify rt_default-host.h.in directly. What do you think about making the followings changes?
> 
> ```diff
> $ diff --git a/extensions/rt_default/meson.build b/extensions/rt_default/meson.build
> index 28c3d67..9d79aa4 100644
> --- a/extensions/rt_default/meson.build
> +++ b/extensions/rt_default/meson.build
> @@ -2,8 +2,7 @@ if cc.has_function('regexec', prefix : '#include <regex.h>')
>    conf_data = configuration_data()
>    conf_data.set('HAVE_REG_STARTEND', 1)
>  endif
> -configure_file(input : 'rt_default-host.h.in',
> -                output : 'rt_default-host.h',
> +configure_file(output : 'rt_default-host.h',
>                  configuration : conf_data)
> ```
>

I modified directly `rt_default-host.h.in` because meson build error.
but with your suggest to adjust `configure_file` function arguments. It works fine without having to modify the source files directly. So your changes are undoubtedly better.

> freeDiameter is using an older version of the syntax.
> 
> ```
> $ ninja        
> [138/3941] Generating from 'subproject...er/extensions/rt_default/rtd_conf.y'..
> ../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y:42.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
>    42 | %error-verbose
>       | ^~~~~~~~~~~~~~
>       | %define parse.error verbose
> ../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y:49.1-12: warning: deprecated directive: ‘%pure-parser’, use ‘%define api.pure’ [-Wdeprecated]
>    49 | %pure-parser
>       | ^~~~~~~~~~~~
>       | %define api.pure
> ../subprojects/freeDiameter/extensions/rt_default/rtd_conf.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
> [3941/3941] Linking target tests/non3gpp/non3gpp
> ```
> 
> You might consider modifying it as follows.
> 
> ```diff
> $ diff --git a/extensions/rt_default/rtd_conf.y b/extensions/rt_default/rtd_conf.y
> index e02303c..1ef24ab 100644
> --- a/extensions/rt_default/rtd_conf.y
> +++ b/extensions/rt_default/rtd_conf.y
> @@ -39,14 +39,14 @@
>  
>  /* For development only : */
>  %debug 
> -%error-verbose
> +%define parse.error verbose
>  
>  /* The parser receives the configuration file filename as parameter */
>  %parse-param {char * conffile}
>  
>  /* Keep track of location */
>  %locations 
> -%pure-parser
> +%define api.pure
>  
>  %{
>  #include "rt_default.h"
> ```

I'm not familiar with bison, I'm sorry I didn't notice this error when compiling.
I try to use new directive with your hint. And it works fine.

Thanks again for your valuable advice!

**Comment by acetcom** [comment]
@Crazyokd You haven't asked for a pull request in the way I suggested yet, do you plan to resubmit it?

**Comment by Crazyokd** [comment]
@acetcom 
OK, please review again.
Thank you.

**Pull request merged**
